const express = require('express')
const morgan = require('morgan')
const bodyParser = require('body-parser')
const user_routes = require('./routes/user.routes')
const authenticationroutes = require('./routes/authentication.routes')
const studentenhuisroutes = require('./routes/studentenhuis.routes')
const AuthController = require('./controllers/authentication.controller')
const ApiError = require('./model/ApiError')
const settings = require('./config/config')
const db = require('./config/db.improved');

const port = process.env.PORT || settings.webPort

let app = express()

const expressSwagger = require('express-swagger-generator')(app);

let options = {
	swaggerDefinition: {
		info: {
			description: 'Deze server toont de API beschrijving van de Nodejs server uit de eindopdracht van Programmeren 4, periode 4, kans 1.',
			title: 'Avans Programmeren 4 - Studentenhuis casus'
		},
		// host: 'localhost:3000',
		host: 'mee-eten.herokuapp.com',
		produces: [
			"application/json"
		],
		securityDefinitions: {
			Bearer: {
				type: "apiKey",
				name: "Authorization",
				in: "header",
				description: "For accessing the API a valid JWT token must be passed in all the" +
					"queries in the 'Authorization' header. A valid JWT token is generated by the" +
					"API and retourned as answer of a call to the route /api/login and /api/register" +
					"giving a valid user & password. \n\n The following syntax must be used in the " +
					"'x-access-token' header : \n\n xxxxxx.yyyyyyy.zzzzzz",
				value: "xx.ff.tt"
			}
		}
	},
	basedir: __dirname, //app absolute path
	files: ['./routes/**/*.js'], //Path to the API handle folder,
	securitySchemes: {
		bearerAuth: {
			type: "http",
			scheme: "bearer",
			bearerFormat: "JWT"
		}
	}
};
expressSwagger(options)

// bodyParser parses the body from a request
app.use(bodyParser.json())

// Instal Morgan as logger
app.use(morgan('dev'))

// Add CORS headers
app.use(function (req, res, next) {
	res.setHeader('Access-Control-Allow-Origin', 'http://localhost:3000');
	res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');
	res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');
	res.setHeader('Access-Control-Allow-Credentials', true);
	next();
});

// Preprocessing catch-all endpoint
// The perfect place to check that the user performing the request 
// has authorisation to do things on our server
app.use('*', function (req, res, next) {
	next()
})

// Unprotected routes - no token required.
// Provides login and registration 
app.use('/api', authenticationroutes)

// On all other routes, check for API key
// app.all('*', (req, res, next) => { });
app.all('*', AuthController.validateToken);

// Regular endpoints
app.use('/api', user_routes)
app.use('/api', studentenhuisroutes)

// Postprocessing; catch all non-existing endpoint requests
app.use('*', function (req, res, next) {
	// console.log('Non-existing endpoint')
	const error = new ApiError("Deze endpoint bestaat niet", 404)
	next(error)
})

// Catch-all error handler according to Express documentation - err should always be an ApiError! 
// See also http://expressjs.com/en/guide/error-handling.html
app.use((err, req, res, next) => {
	// console.dir(err)
	res.status((err.code || 404)).json(err).end()
})

// Start listening for incoming requests.
app.listen(port, () => {
	console.log('Server running on port ' + port)
})

// Testcases need our app - export it.
module.exports = app